[project]
name = "wallege"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8,<3.10"
dependencies = [
    "onnxruntime>=1.19.2",
    "rembg>=2.0.61",
    "opencv-python>=4.8.0",
    "pillow>=10.0.0",
    "numpy>=1.24.0",
]
